/* Independent, session-random sky events. Everything follows the scene clock,
   including scheduling, so pause and inactive views freeze the entire sky. */
import {createCelestialBodies} from './celestial-bodies.js?v=20260911-depth2';
const TAU=Math.PI*2,clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v)),range=(a,b)=>a+Math.random()*(b-a),gap=(min,mean,max)=>Math.min(max,min-Math.log(1-Math.random())*mean);
const add=(a,b)=>a.map((v,k)=>v+b[k]),mul=(a,s)=>a.map(v=>v*s),unit=a=>{const l=Math.hypot(...a);return a.map(v=>v/l);},cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]];
const gold=[1,.70,.30],ice=[.49,.84,1],violet=[.70,.47,1];
function direction(){const z=range(-1,1),a=range(0,TAU),r=Math.sqrt(1-z*z);return[r*Math.cos(a),z,r*Math.sin(a)];}

export function createCosmicEvents(gl,program,buffer){
 const actors=Array.from({length:12},(_,i)=>({id:'cosmic-'+i,renderable:false,emphasis:1,worldPosition:[0,0,0],body:{type:1,radius:8,seed:Math.random(),color:gold,tilt:range(.2,1.4),satellite:false}})),bodies=createCelestialBodies(gl,program,buffer,actors);
 const points=new Float32Array(7000*8),lines=new Float32Array(14000*7),pointGPU=buffer(points,gl.DYNAMIC_DRAW),lineGPU=buffer(lines,gl.DYNAMIC_DRAW);let pc=0,lc=0;
 const effectProgram=program('precision highp float;attribute vec3 aPosition;attribute vec3 aColor;attribute vec2 aStyle;uniform mat4 uMVP;uniform float uDPR;uniform float uLimit;varying vec3 vColor;varying float vAlpha;void main(){vec4 c=uMVP*vec4(aPosition,1.0);gl_Position=c;gl_PointSize=clamp(aStyle.x*uDPR*1260.0/max(c.w,150.0),1.0,uLimit);vColor=aColor;vAlpha=aStyle.y;}',
 'precision mediump float;uniform float uPoints;varying vec3 vColor;varying float vAlpha;void main(){float a=vAlpha;if(uPoints>.5){vec2 p=gl_PointCoord*2.0-1.0;float r=dot(p,p);if(r>1.0)discard;a*=exp(-r*5.0);}gl_FragColor=vec4(vColor,a);}');
 const ea=[['aPosition',3,0],['aColor',3,12],['aStyle',2,24]].map(([n,s,o])=>[gl.getAttribLocation(effectProgram,n),s,o]),eu={};for(const n of['uMVP','uDPR','uLimit','uPoints'])eu[n]=gl.getUniformLocation(effectProgram,n);const pointLimit=gl.getParameter(gl.ALIASED_POINT_SIZE_RANGE)[1];
 const lineProgram=program('attribute vec3 aPosition;attribute vec4 aColor;uniform mat4 uMVP;varying vec4 vColor;void main(){gl_Position=uMVP*vec4(aPosition,1.0);vColor=aColor;}','precision mediump float;varying vec4 vColor;void main(){gl_FragColor=vColor;}'),la=[['aPosition',3,0],['aColor',4,12]].map(([n,s,o])=>[gl.getAttribLocation(lineProgram,n),s,o]),lm=gl.getUniformLocation(lineProgram,'uMVP');
 const portalProgram=program(`precision highp float;attribute vec3 aPosition;attribute vec4 aColor;attribute vec2 aMotion;uniform mat4 uMVP;uniform vec3 uOrigin;uniform vec3 uRight;uniform vec3 uUp;uniform vec3 uBack;uniform float uRadius;uniform float uKind;uniform float uTime;uniform float uSurge;varying vec4 vColor;
 void main(){float r=aPosition.x,a=aPosition.y+uTime*aMotion.x,z=aPosition.z;vec3 p;
  if(uKind<.5){p=aMotion.y>.5?vec3(cos(a)*r,sin(a)*r,0.0):vec3(cos(a)*r,sin(a)*r*.23+sin(a*3.0+uTime)*.018,sin(a)*r*.973);}
  else{p=vec3(cos(a)*r+.055*sin(z*3.0+uTime*.5),sin(a)*r*.86,z+sin(a)*r*.36);}
  vec3 w=uOrigin+(uRight*p.x+uUp*p.y+uBack*p.z)*uRadius;gl_Position=uMVP*vec4(w,1.0);float hot=.55+.45*pow(.5+.5*cos(aPosition.y*2.0-uTime*1.8+z*3.0),6.0);vColor=vec4(aColor.rgb,aColor.a*hot*(1.0+uSurge*1.6));
 }`,'precision mediump float;varying vec4 vColor;void main(){gl_FragColor=vColor;}');
 const pa=[['aPosition',3,0],['aColor',4,12],['aMotion',2,28]].map(([n,s,o])=>[gl.getAttribLocation(portalProgram,n),s,o]),pu={};for(const n of['uMVP','uOrigin','uRight','uUp','uBack','uRadius','uKind','uTime','uSurge'])pu[n]=gl.getUniformLocation(portalProgram,n);
 function makePortal(kind){const data=[];function trace(fn,color,alpha,rate,steps=120,optical=0){let prev=fn(0);for(let j=1;j<=steps;j++){const q=fn(j/steps);for(const p of[prev,q])data.push(...p,...color,alpha,rate,optical);prev=q;}}
  if(!kind){for(let k=0;k<62;k++){const r=1.40+k/61*2.05;trace(t=>[r,t*TAU+k*.73,0],k%5?gold:[1,.91,.67],k%8===0?.34:.18,.30+.66/r);}for(const r of[1.045,1.072,1.12])trace(t=>[r,t*TAU,0],[1,.84,.48],.65,.18,160,1);}
  else{for(let k=0;k<13;k++){const r=2.3*Math.exp(-k*.17),z=-k*.30;trace(t=>[r,t*TAU,z],k%2?ice:violet,.27-k*.010,.27+k*.04);}for(let k=0;k<22;k++)trace(t=>[2.3*Math.exp(-t*2.04),k/22*TAU+t*TAU*2.8,-t*3.60],k%2?ice:violet,.14,.46,140);for(const r of[2.28,2.34])trace(t=>[r,t*TAU,0],[.70,.94,1],.34,.36,160);}
  return{gpu:buffer(new Float32Array(data)),count:data.length/9};
 }
 const portalGeometry=[makePortal(0),makePortal(1)],portals=[{name:'black-hole',screen:[0,0],origin:[0,0,0],radius:1,frame:null},{name:'wormhole',screen:[0,0],origin:[0,0,0],radius:1,frame:null}];
 let layoutKey='',events=[],next={},counts={},history=[],serial=0,lastTime=0,frameArgs=null;
 function reset(){events=[];next={meteor:range(1.8,4.8),asteroid:range(4,9),collapse:range(9,17),surge:range(6,13)};counts={meteor:0,asteroid:0,collapse:0,surge:0};history=[];lastTime=0;}
 function cameraPoint(x,y,depth,args){const f=args.height/(2*Math.tan(21*Math.PI/180)),distance=args.basis.distance,target=args.cameraTarget;return target.map((v,k)=>v+args.basis.back[k]*(distance-depth)+args.basis.right[k]*(x-args.width*(.5+args.center*.5))*depth/f+args.basis.up[k]*(args.height*.4925-y)*depth/f);}
 function layout(args){const key=[args.width,args.height,args.center].join('|');if(key===layoutKey)return;layoutKey=key;const h=args.home,sy=Math.sin(h.yaw),cy=Math.cos(h.yaw),sp=Math.sin(h.pitch),cp=Math.cos(h.pitch),right=[cy,0,-sy],up=[-sy*sp,cp,-cy*sp],back=[sy*cp,sp,cy*cp],distance=h.distance*Math.max(1,1350/args.width),basis={right,up,back,distance},base={...args,basis,cameraTarget:h.target},eye=h.target.map((v,k)=>v+back[k]*distance),f=args.height/(2*Math.tan(21*Math.PI/180));
  [[.73,.70,1800,27],[.31,.27,2150,23]].forEach(([x,y,d,r],i)=>{const p=portals[i];p.screen=[x*args.width,y*args.height];p.origin=cameraPoint(...p.screen,d,base);p.radius=r*d/f;const b=unit(eye.map((v,k)=>v-p.origin[k])),rgt=unit(cross(up,b));p.frame={right:rgt,up:cross(b,rgt),back:b};});
 }
 function freePosition(args,radius=65){for(let i=0;i<40;i++){const x=range(args.width*.29,args.width*.91),y=range(args.height*.14,args.height*.81);if(args.obstacles.some(b=>x+radius>b.x&&x-radius<b.x+b.w&&y+radius>b.y&&y-radius<b.y+b.h))continue;if(args.clusters.some(g=>g.screen&&Math.hypot(x-g.screen.x,y-g.screen.y)<radius+52))continue;if(portals.some(p=>Math.hypot(x-p.screen[0],y-p.screen[1])<radius+90))continue;return[x,y];}return[args.width*.52,args.height*.73];}
 function spawn(type,args){const time=args.time,depth=range(1080,1780),pixel=depth/(args.height/(2*Math.tan(21*Math.PI/180))),id=++serial,e={id,type,start:time,life:8,seed:Math.random(),pixel,color:Math.random()<.55?gold:ice,basis:{right:[...args.basis.right],up:[...args.basis.up],back:[...args.basis.back]}};
  if(type==='meteor'){e.life=3.5;e.members=[];const fromRight=Math.random()<.70,angle=range(.22,.68),count=Math.floor(range(3,8));for(let i=0;i<count;i++){const speed=range(370,650)*pixel,x=fromRight?range(.79,1.03)*args.width:range(.26,.40)*args.width,y=range(.06,.36)*args.height;e.members.push({origin:cameraPoint(x,y,depth,args),velocity:args.basis.right.map((v,k)=>v*(fromRight?-1:1)*Math.cos(angle)*speed-args.basis.up[k]*Math.sin(angle)*speed-args.basis.back[k]*range(20,50)),delay:i*range(.10,.21),life:range(1.2,2.5),tail:range(.13,.27)});}}
  if(type==='asteroid'){e.life=range(5,8);e.members=[];e.captured=Math.random()<.30;const count=Math.floor(range(1,4));for(let i=0;i<count;i++){const xy=freePosition(args,24),origin=cameraPoint(xy[0],xy[1],depth,args),speed=range(75,145)*pixel;e.members.push({origin,velocity:args.basis.right.map((v,k)=>-v*speed-args.basis.up[k]*range(25,65)*pixel),radius:range(4,8)*pixel,seed:Math.random(),angle:range(0,TAU),orbit:range(4.0,6.0)});}}
  if(type==='collapse'){e.life=12;e.screen=freePosition(args,94);e.origin=cameraPoint(...e.screen,depth,args);e.radius=range(8,13)*pixel;e.color=Math.random()<.60?[1,.66,.29]:[.50,.75,1];e.sparks=Array.from({length:Math.floor(range(380,620))},()=>({dir:direction(),speed:range(11,54)*pixel,seed:Math.random(),size:range(.8,2.6)}));}
  if(type==='surge'){e.life=range(4,7);e.portal=Math.random()<.55?0:1;e.sparks=Array.from({length:90},()=>({angle:range(0,TAU),radius:range(2.8,5),offset:Math.random()}));}
  events.push(e);counts[type]++;history.push({id,type,at:time,variant:type==='asteroid'?(e.captured?'capture':'drift'):type==='surge'?portals[e.portal].name:'',position:e.screen||null});if(history.length>18)history.shift();
 }
 function update(args){frameArgs=args;lastTime=args.time;layout(args);for(const p of portals){const v=p.origin,m=args.matrix,d=m[3]*v[0]+m[7]*v[1]+m[11]*v[2]+m[15],x=m[0]*v[0]+m[4]*v[1]+m[8]*v[2]+m[12],y=m[1]*v[0]+m[5]*v[1]+m[9]*v[2]+m[13];p.screen=[(x/d*.5+.5)*args.width,(.5-y/d*.5)*args.height];}events=events.filter(e=>args.time-e.start<e.life);for(const type of Object.keys(next))if(args.time>=next[type]){if(events.length>=7){next[type]=args.time+range(1.5,3);continue;}spawn(type,args);next[type]=args.time+(type==='meteor'?gap(3,5,18):type==='asteroid'?gap(8,10,30):type==='collapse'?gap(25,20,80):gap(11,14,50));}}
 function point(p,c,size,alpha){if(alpha<.001||pc+8>points.length)return;points[pc++]=p[0];points[pc++]=p[1];points[pc++]=p[2];points[pc++]=c[0];points[pc++]=c[1];points[pc++]=c[2];points[pc++]=size;points[pc++]=alpha;}
 function line(a,b,c,alpha){if(alpha<.001||lc+14>lines.length)return;for(const p of[a,b]){lines[lc++]=p[0];lines[lc++]=p[1];lines[lc++]=p[2];lines[lc++]=c[0];lines[lc++]=c[1];lines[lc++]=c[2];lines[lc++]=alpha;}}
 function actor(i,p,r,type,color,seed=0.3){const a=actors[i];a.renderable=true;a.worldPosition=p;a.body.radius=r;a.body.type=type;a.body.color=color;a.body.seed=seed;}
 function portalPoint(portal,p){const f=portal.frame;return portal.origin.map((v,k)=>v+(f.right[k]*p[0]+f.up[k]*p[1]+f.back[k]*p[2])*portal.radius);}
 function surge(i,time){return Math.max(0,...events.filter(e=>e.type==='surge'&&e.portal===i).map(e=>Math.sin(clamp((time-e.start)/e.life)*Math.PI)));}
 function drawPortals(args){update(args);for(const a of actors)a.renderable=false;gl.useProgram(portalProgram);gl.uniformMatrix4fv(pu.uMVP,false,args.matrix);gl.uniform1f(pu.uTime,args.time);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE);gl.disable(gl.DEPTH_TEST);gl.depthMask(false);
  portals.forEach((p,i)=>{gl.uniform3fv(pu.uOrigin,p.origin);for(const k of['Right','Up','Back'])gl.uniform3fv(pu['u'+k],p.frame[k.toLowerCase()]);gl.uniform1f(pu.uRadius,p.radius);gl.uniform1f(pu.uKind,i);gl.uniform1f(pu.uSurge,surge(i,args.time));gl.bindBuffer(gl.ARRAY_BUFFER,portalGeometry[i].gpu);for(const[a,s,o]of pa){gl.enableVertexAttribArray(a);gl.vertexAttribPointer(a,s,gl.FLOAT,false,36,o);}gl.drawArrays(gl.LINES,0,portalGeometry[i].count);});for(const[a]of pa)gl.disableVertexAttribArray(a);
  actor(0,portals[0].origin,portals[0].radius,6,[.001,.001,.002]);actor(1,portalPoint(portals[1],[0,0,-3.6]),portals[1].radius*.28,6,[.001,.002,.005]);bodies.draw({matrix:args.matrix,time:args.time,eye:args.eye,focal:args.height/(2*Math.tan(21*Math.PI/180))*args.dpr,opacity:1,activeId:null});
 }
 function asteroidPoint(e,m,age){if(e.captured){const t=clamp(age/e.life),r=m.orbit*(1-t)+.75,a=m.angle+t*TAU*1.35;return portalPoint(portals[0],[Math.cos(a)*r,Math.sin(a)*r*.38,Math.sin(a)*r*.95]);}return m.origin.map((v,k)=>v+m.velocity[k]*age-e.basis.up[k]*age*age*3*e.pixel);}
 function ring(center,basis,r,color,alpha,tilt=.15){let last=null;for(let k=0;k<=128;k++){const a=k/128*TAU,p=center.map((v,i)=>v+basis.right[i]*Math.cos(a)*r+(basis.up[i]*Math.cos(tilt)+basis.back[i]*Math.sin(tilt))*Math.sin(a)*r);if(last)line(last,p,color,alpha);last=p;}}
 function drawEvents(args){pc=0;lc=0;for(const a of actors)a.renderable=false;let ai=2;
  for(let k=0;k<64;k++){const t=(k/64+args.time*.063)%1,r=2.3*Math.exp(-t*2.04),a=k*.618034*TAU+t*TAU*2.8+args.time*.46;point(portalPoint(portals[1],[Math.cos(a)*r,Math.sin(a)*r*.86,-t*3.60+Math.sin(a)*r*.36]),k%3?ice:violet,2.8,Math.sin(t*Math.PI)*.52);}
  for(const e of events){const age=args.time-e.start;
   if(e.type==='meteor')for(const m of e.members){const a=age-m.delay;if(a<0||a>m.life)continue;const fade=Math.min(1,a*8,(m.life-a)*3),head=m.origin.map((v,k)=>v+m.velocity[k]*a);point(head,e.color,4.8,fade*.95);for(let k=0;k<22;k++){const q=k/22,q2=(k+1)/22,p=m.origin.map((v,j)=>v+m.velocity[j]*Math.max(0,a-q*m.tail)),p2=m.origin.map((v,j)=>v+m.velocity[j]*Math.max(0,a-q2*m.tail));line(p,p2,e.color,Math.pow(1-q,2)*fade*.85);}}
   if(e.type==='asteroid')for(const m of e.members){const fade=clamp(age*2)*clamp((e.life-age)*1.7),p=asteroidPoint(e,m,age);if(ai<actors.length)actor(ai++,p,m.radius*(e.captured?clamp((e.life-age)*1.5):1),1,[.42,.30,.20],m.seed);point(p,[1,.60,.26],m.radius/e.pixel*3.2,fade*.20);for(let k=0;k<15;k++){const q=k/15,p1=asteroidPoint(e,m,Math.max(0,age-q*.45)),p2=asteroidPoint(e,m,Math.max(0,age-(q+.067)*.45));line(p1,p2,[.82,.49,.25],Math.pow(1-q,2)*fade*.34);point(p1,[.60,.43,.30],3+q*9,Math.pow(1-q,2)*fade*.035);}}
   if(e.type==='surge'){const p=portals[e.portal],phase=age/e.life,fade=Math.sin(phase*Math.PI);for(const s of e.sparks){const t=(phase+s.offset)%1,r=s.radius*(1-t)+.6,a=s.angle+t*TAU*(e.portal?2.0:1.45),q=e.portal?[Math.cos(a)*r*.65,Math.sin(a)*r*.65,-t*3.8]:[Math.cos(a)*r,Math.sin(a)*r*.23,Math.sin(a)*r*.97];point(portalPoint(p,q),e.portal?ice:gold,3.4,Math.sin(t*Math.PI)*fade*.65);}}
   if(e.type==='collapse'){const blast=age-2.55;if(blast<0){const collapse=clamp((age-1.55)/1),r=e.radius*(1-collapse*.90)*(1+Math.sin(age*7)*.03);if(ai<actors.length)actor(ai++,e.origin,r,0,[.76,.86,1],e.seed);point(e.origin,ice,30+collapse*30,.15+collapse*.2);for(let k=0;k<32;k++){const a=k/32*TAU,rr=e.radius*(3.8-collapse*3),p=e.origin.map((v,i)=>v+e.basis.right[i]*Math.cos(a+age)*rr+e.basis.up[i]*Math.sin(a+age)*rr);point(p,ice,2.2,collapse*.65);}}
    else{const fade=Math.exp(-blast*.33);if(ai<actors.length)actor(ai++,e.origin,e.pixel*(1.7+5*Math.exp(-blast*2.6)),0,blast<1?[1,.95,.84]:ice,e.seed);point(e.origin,[1,.89,.70],140*Math.exp(-blast)+7,Math.exp(-blast*1.6)*.88);const r=(12+155*(1-Math.exp(-blast*.53)))*e.pixel,alpha=clamp(blast*5)*Math.exp(-blast*.43);ring(e.origin,e.basis,r,e.color,alpha*.64,.34);ring(e.origin,e.basis,r*1.025,ice,alpha*.30,.34);
     for(const s of e.sparks){const d=s.speed*Math.pow(blast,.83),p=e.origin.map((v,k)=>v+s.dir[k]*d),c=e.color.map((v,k)=>v*(.65+.35*fade));point(p,c,s.size,fade*(.25+s.seed*.50));if(s.seed>.82){const tail=e.origin.map((v,k)=>v+s.dir[k]*Math.max(0,d-s.speed*.15));line(tail,p,c,fade*.32);}if(s.seed<.09)point(p,c,18+s.seed*130,fade*.025);}
    }
   }
  }
  bodies.draw({matrix:args.matrix,time:args.time,eye:args.eye,focal:args.height/(2*Math.tan(21*Math.PI/180))*args.dpr,opacity:1,activeId:null});gl.disable(gl.DEPTH_TEST);gl.depthMask(false);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE);
  if(lc){gl.useProgram(lineProgram);gl.uniformMatrix4fv(lm,false,args.matrix);gl.bindBuffer(gl.ARRAY_BUFFER,lineGPU);gl.bufferSubData(gl.ARRAY_BUFFER,0,lines.subarray(0,lc));for(const[a,s,o]of la){gl.enableVertexAttribArray(a);gl.vertexAttribPointer(a,s,gl.FLOAT,false,28,o);}gl.drawArrays(gl.LINES,0,lc/7);for(const[a]of la)gl.disableVertexAttribArray(a);}
  if(pc){gl.useProgram(effectProgram);gl.uniformMatrix4fv(eu.uMVP,false,args.matrix);gl.uniform1f(eu.uDPR,args.dpr);gl.uniform1f(eu.uLimit,pointLimit);gl.uniform1f(eu.uPoints,1);gl.bindBuffer(gl.ARRAY_BUFFER,pointGPU);gl.bufferSubData(gl.ARRAY_BUFFER,0,points.subarray(0,pc));for(const[a,s,o]of ea){gl.enableVertexAttribArray(a);gl.vertexAttribPointer(a,s,gl.FLOAT,false,32,o);}gl.drawArrays(gl.POINTS,0,pc/8);for(const[a]of ea)gl.disableVertexAttribArray(a);}gl.depthMask(true);
 }
 reset();
 return{reset,drawPortals,drawEvents,getState:()=>({counts:{...counts},next:{...next},active:events.map(e=>({id:e.id,type:e.type,age:lastTime-e.start,phase:e.type==='collapse'?(lastTime-e.start<1.55?'star':lastTime-e.start<2.55?'collapse':'explosion'):e.type,variant:e.captured?'capture':e.type==='surge'?portals[e.portal].name:'',screen:e.screen||null})),recent:[...history],portals:portals.map(p=>({name:p.name,screen:p.screen})),points:pc/8,lineVertices:lc/7}),destroy(){bodies.destroy();for(const b of[pointGPU,lineGPU,...portalGeometry.map(p=>p.gpu)])gl.deleteBuffer(b);for(const p of[effectProgram,lineProgram,portalProgram])gl.deleteProgram(p);}};
}
